spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qwe7744066
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf-8
  mail:
    host: smtp.qq.com
    username: 973013625@qq.com
    password: gfazcnkqgloibfdg
    port: 587
    #默认的邮件编码为UTF-8
    default-encoding: UTF-8
    properties:
      from: 973013625@qq.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  redis:
    database: 0
    host: localhost
    port: 6379
mybatis-plus:
  type-aliases-package: com.sec.entity
  mapper-locations: classpath:mappers/*Mapper.xml
# 123
